climatepolicyradar/knowledge-graph

scripts/evaluate.py
static_sites/concept_librarian/__main__.py
static_sites/concept_librarian/template.py
static_sites/concept_librarian/templates/concept.html
tests/test_evaluate.py

already deployed, eg https://djhoyps9k9bag.cloudfront.net/Q989.html

add issues from subconcepts to librarian concept pages

---

src/argilla.py
static_sites/labelling_librarian/checks.py
static_sites/labelling_librarian/templates/dataset.html
static_sites/labelling_librarian/templates/index.html

adds a dataset-level check for low inter-annotator agreement
also makes a couple of minor tweaks to the templates to ensure that dark mode styles are properly applied 😎

labelling librarian check for low IAA

---

flows/index.py

---
- Is updating the default ingest config to run as a deployment not subflow.

Updating the default ingest config to run as a deployment not subflow.

---

deployments.py
flows/index.py

--- 
- Adds a deployment for the flow that runs partial updates on a batch of documents. 
Why wasn't this raised as an error in the previous unit tests on [this ](https://github.com/climatepolicyradar/knowledge-graph/pull/263)PR? 
- We run deployments as flows during testing.

Adding a deployment for the partial updates on batch of docs.

---

flows/wikibase_to_s3.py
tests/flows/test_wikibase_to_s3.py

If there are extras in S3, that are not in Wikibase, we now delete them.
There's some minor changes elsewhere, as suggested by my LSP.
TOWARDS PLA-469

feat(wikibase): Delete missing extras from S3

---

deployments.py

This is from this deployment being re-enabled.

fix: Remove commented comment

---

tests/flows/test_index.py

The flakiness appears to have gone.

ci: Update flaky on CI markers

---

flows/count_family_document_concepts.py

This is part of understanding when updates/removals are happening.

feat: Clarify behaviour around updates/removals

---

flows/inference.py
tests/flows/test_inference.py

This is so downstream, we know to do removals.

feat: Save empty inference results

---

scripts/clean_labelled_passages_directory.py

---
- Adds a script for cleaning up the labelled passages directory. 
- This is required as we have outputs that are from non-english languages (e.g. we have run inference on french docs for example).

Adding a script for cleaning the labelled passages directory.

---

deployments.py
flows/boundary.py
flows/count_family_document_concepts.py
flows/deindex.py
flows/index.py
flows/utils.py
tests/flows/test_boundary.py
tests/flows/test_count_family_document_concepts.py
tests/flows/test_deindex.py
tests/flows/test_index.py
tests/flows/test_utils.py

I found it easy to think about this as the boundaries, and where we traverse them. This isn't the final step in sharing, but is a good start imo.

refactor: Share code between flows for systems boundaries

---

.github/workflows/bump.yml

This was hastily disabled as part of a security risk.
FIXES PLA-486

build: Re-enable Pre-commit check

---

.pre-commit-config.yaml
scripts/build_dataset/02_download_litigation.py
scripts/cloud.py
scripts/demote.py
scripts/promote.py
src/exceptions.py
tests/flows/test_count_family_document_concepts.py
tests/flows/test_index.py
tests/test_identifiers.py
tests/test_promote.py

I'm temporarily reverted the Pyright version change, since it added a bunch of (reasonable) errors.
FIXES PLA-486

build: Reflect latest formatting

---

flows/boundary.py

In https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/fd984a38-16fe-48bf-b246-237c39c4c632, the `updates-by-s3` pipeline passed, but if you look in it, there was a failed task, so overall it should've been reported as failed.
The approach is the same used elsewhere[^1][^2].
[^1]: https://github.com/climatepolicyradar/knowledge-graph/blob/fix%2Freport-flow-state-type-failures/flows/deindex.py#L318-L340
[^2]:

fix: Check for Prefect state failures

---

flows/boundary.py
flows/count_family_document_concepts.py
flows/deindex.py

fix: Surface more errors

---

automations.py

Until we're confident.
FIXES PLA-511

fix: Disable backup → inference automation

---

poetry.lock
pyproject.toml
scripts/upload_targets_data.py
src/labelled_passage.py

Finalising the previous removal of legacy code, by removing the `argilla-v1` dependency and all references to it in the codebase.

remove argilla v1 dependency

---

automations.py

I pre-emptively merged the other PR, in some local machine silliness of mine.
**Testing**
Successful deployment: https://github.com/climatepolicyradar/knowledge-graph/actions/runs/14306323617/job/40090951543
FIXES PLA-468

fix: Use latest Prefect v3 schemas

---

flows/inference.py

---
- Is a bug fix for a failing inference [run](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/e3cfd624-3bad-4cdd-8977-f0e2f584b27d?entity_id=e3cfd624-3bad-4cdd-8977-f0e2f584b27d).

Bugfix don't await.

---

flows/utils.py

Could be expanded later to be opt-in for non-production.

refactor: Don't notify on non-production failures

---

scripts/do_classifier_specs_have_results.py

---
- Adds a script for identifying whether classifiers have outputs in s3 or not. 
_Note: This was a 2 minute write and I have no complaint if this isn't merged. Just putting here in case others find it useful as well._

Adding a helper script for identifying whether classifiers have outputs.

---

tests/local_vespa/test_app/schemas/family_document.sd

See https://github.com/climatepolicyradar/navigator-infra/pull/1050

:robot: enable document title bm25 search

---

flows/boundary.py

It was out-of-date.
FIXES PLA-505

docs: Update serialisation comment

---

flows/deindex.py

fix: Remove incomplete comment

---

flows/boundary.py

Similar to https://github.com/climatepolicyradar/knowledge-graph/pull/398, but for all remaining uses.
I did change it to use the default Python logger, but changed to `print` statements after readig this[^1]:
> get_run_logger() can only be used in the context of a flow or task.
>
> To use a normal Python logger anywhere with your same configuration, use get_logger() from prefect.logging.
>
> The logger retrieved with get_logger() will not send log records to the Prefect API.
TOWARDS PLA-573
[^1]: https://docs.prefect.io/v3/develop/logging

fix: Don't log and print instead

---

Dockerfile
flows/boundary.py
pyproject.toml

Trying to get more info from stacktraces/logging and also to see the memory usage when getting document passages.
TOWARDS PLA-573

build: Add debugging/reporting

---

flows/count_family_document_concepts.py

Having these values available will help with debugging and auditing the concept counts document summaries

Log what we are expecting to put into vespa

---

flows/boundary.py

Adds logging that will print the path for the concept_counts summary so we can more easily go and confirm its being written correctly

Confirm write out path for concept counts

---

flows/boundary.py

---
- Adds additional logging to the call back used in the indexing pipeline.

Updating the callback logging for the indexing pipeline.

---

.github/workflows/ci.yml
flows/boundary.py
pyproject.toml

Same motivation, and implementation, as #421.
FIXES PLA-615

refactor: Allow flexible concurrency for sub-Deployments

---

flows/aggregate_inference_results.py

I moved this to the batch level because I thought it would make more sense visually in prefect, but I've since realised I could have my cake and eat it by having tasks at both levels

refactor: make each document a task again

---

flows/aggregate_inference_results.py
tests/flows/test_aggregate_inference_results.py

Rather than reinitialising the session for every document.
[As suggested here](https://github.com/climatepolicyradar/knowledge-graph/pull/482#discussion_r2133766947)

fix: Initialise session at batch level

---

automations.py

Was missed as part of #489 and caused a deployoyment failure[^1].
FIXES PLA-654
[^1]: https://github.com/climatepolicyradar/knowledge-graph/actions/runs/15554552324/job/43792051238

fix: Remove ununsed automation

---

automations.py

I missed automations off the previous change. We changed the flow name and the prefix, but the prefix change wasnt being applied here leading to a 404

fix: update automation deployment name

---

.pre-commit-config.yaml
.rules/use-walrus-operator.yaml
flows/boundary.py
flows/utils.py
scripts/audit/do_outputs_align_for_a_document.py
scripts/promote.py
sgconfig.yml
src/concept.py
src/sampling.py
src/wikidata.py
static_sites/concept_librarian/checks.py
static_sites/vibe_check/__main__.py

The walrus operator is a nice, and modern way, to be succinct.
Adding ast-grep lets us expand the repository with further rules.
These were all automatically fixed with `ast-grep scan --update-all`.

ci: Add ast-grep linting

---

poetry.lock
pyproject.toml

So we can use it in Prefect and via the CLI.
TOWARDS PLA-758

chore(deps): Add Coiled

---

scripts/predict.py
scripts/train.py
scripts/utils.py

Following on from [discussion on a previous PR](https://github.com/climatepolicyradar/knowledge-graph/pull/556#discussion_r2244776090), where I agreed to follow up on this separately

Represent model path with a pydantic model

---

automations.py

This was updated today so needs updating here too: https://github.com/climatepolicyradar/navigator-data-s3-backup/pull/82/files

fix: correct name for deploys after change

---

tests/flows/test_inference.py

Trying out a nicer model for mocking that acts more as a customisable mock builder then our hardcoded mocks we typically use. There are existing mocks for `run_deployment` in `test_infer` and `test_index`, if this turns out to be enjoyed here we could expand it there too.
This is an experiment that I've only applied to one test, so it does look a little overblown right now!

test: use a generator mock for run_deployment

---

flows/classifier_specs/v2/prod.yaml
flows/classifier_specs/v2/staging.yaml

Add 15 new signed-off classifiers to v2 specs

---

justfile
knowledge_graph/identifiers.py
knowledge_graph/wikibase.py
mcp/Dockerfile
mcp/README.md
mcp/infra/Pulumi.labs.yaml
mcp/infra/Pulumi.yaml
mcp/infra/README.md
mcp/infra/main.py
mcp/server.py
pyproject.toml
uv.lock

Had quite a boring weekend... ended up writing an MCP interface to the concept store 😅
The MCP server uses a `WikibaseSession` to give LLM agents read-only access to content from the concept store. It uses a couple of the new features added to the class in #676, eg concept search, access to help pages, etc
As a result of the changes, I was able to add the locally-running server to the list of my MCP tools in cursor. In a new chat window, I could ask an LLM to use the tools to evaluate the quality of a couple of concepts according to our heuristics and style guide. It was very quickly able to suggest a few changes to specific concepts based on what it saw!
Here's a transcript from cursor - I sent the first message, everything else is the LLM
<details>
<summary>Transcript:</summary>
> can …

Demo mcp server

---

flows/utils.py

Clogging up
https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/068d151a-eec2-7176-8000-39fd93c3e1b0?entity_id=068d151a-eec2-7176-8000-39fd93c3e1b0&state=failed,
for example.

fix: Remove noisy print

---

automations.py

We don't have visibility of this step in #prod-updates, for others in the company to see. Based on a similar approach elsewhere[^1].
**Test**
I deployed to sandbox, and it showed up correctly:
[^1]: https://github.com/climatepolicyradar/navigator-data-pipeline/blob/main/automations/automations.py#L115-L162

feat: Send notification when starting full pipeline

---

scripts/evaluate.py

This function is called in a test, and depending on the ordering, especially when the tests are run concurrently, can mess up other tests[^1].
Ideally there an effect like this isn't needed. For now, cleanup after itself.
TOWARDS PLA-883
[^1]: https://github.com/climatepolicyradar/knowledge-graph/actions/runs/18168137332/job/51717834628

test: Reset manual OS env. setting
