climatepolicyradar/knowledge-graph

src/wikibase.py

These are defined in the env.example but where missed for the env variables when setting up the pipeline copying concepts from wikibase to s3, the result was that the cdn objects ended up without the relationships.
Adding the env variables to the pipeline was the most obvious option, but I figured having them as defaults on the interface client might save us from doing this again, while still allowing for flexibility in changing them by env variable.

Add default property relationship values

---

tests/flows/test_count_family_document_concepts.py

This was failing because the mock concept being chosen was not deterministic

Fix flakey test

---

.gitignore
justfile
tests/local_wikibase/README.md
tests/local_wikibase/docker-compose.dev.yml
tests/local_wikibase/local_wikibase.just
tests/local_wikibase/wikibase_test.env

Docker compose file with config and just commands for spinning up a test instance of wikibase. Resulting in this locally:
No data or tests against it yet, but this seemed like a good point to share back.
This was setup based on an adaption of the advice found [here](https://github.com/wmde/wikibase-release-pipeline/blob/main/deploy/README.md), and through adapting the [linked dockerfile](https://github.com/wmde/wikibase-release-pipeline/blob/main/deploy/docker-compose.yml). These adaptations where done to make it easier to use from a purely test perspective.
1. To remove the need to get an ssl certificate when spinning up the stack. Our use for this instance is very much a local & ci instance, being able to access it without needing a secure connection means we don't need to bother …

Add setup for local test wikibase instance

---

static_sites/concept_librarian/__main__.py
static_sites/concept_librarian/checks.py
static_sites/concept_librarian/template.py

- adds a new check for validating the depth - descendant balance of a concept
- adds traversal methods to the graph, e.g. finding the longest depth, aggregating the number of descendants
The idea came from an issue whereby "Adaptation" got added below "Public Sector" resulting in way too many descendants for some concepts and bloating them. This check is meant to find these spurious links, by checking the depth / descendants ratio. 
NOTE: I've also fixed an issue with `EmptyConcept`. Its inheritence from `Concept` was breaking some downstream functions, so I've made various changes to get this working.
By running on all concepts in the concept store, and inspecting results -- it picks up the above example, but nothing else.
Furthermore, by regenerating the librarian locally, and incepting …

Librarian check for graph depth and node descendants

---

flows/deploy_static_sites.py

If all goes well, this should run the labelling librarian static site generation flow at the same time as the concept librarian one 🕺
I've added the two necessary params to SSM
- `/Argilla/APIKey`
- `/Argilla/APIURL`
The API key corresponds to the existing `prefect-bot-admin` user

add the labelling librarian to the static site generation flow

---

static_sites/labelling_librarian/__main__.py
static_sites/labelling_librarian/template.py
static_sites/labelling_librarian/templates/dataset.html
static_sites/labelling_librarian/templates/index.html

Adding some new features upon request from the policy team:
- datasets alsos show the concept's `preferred_label` now both on the landing page and the dataset pages
- dataset pages have the dataset name showing (this was missing in a previous version)
- datasets in the landing page are filterable by text (both on the preferred label and the qID)
- inspecting and trying the new functionality
- deploying the tool

Labelling librarian improvements

---

Dockerfile
poetry.lock
pyproject.toml

last night's automatic build / deployment of the librarian static sites failed because of a `ModuleNotFoundError` - the `static_sites` directory wasn't discoverable. I've added it to the `pyproject.toml` and `Dockerfile` so it _should_ be discoverable now 🤞
To find out whether this has worked, I'll manually rerun the flow after this PR has been merged.

fix the automatic build / deployment of the librarian static sites

---

poetry.lock
pyproject.toml

Our librarian static site deployment flows are still failing because they can't run the `aws s3 sync` command 🤦‍♂️ 
This PR adds the AWS CLI to the dependencies in `pyproject.toml` so that it should be installed when the docker container is built.

librarian flows need the awscli

---

README.md
docs/docs/developers/justfile.md

The KG repo is open these days, and we expect to see more traffic over here when when the associated features start appearing in product. 
Those newcomers probably won't be interested in which commands we run to promote our models between AWS environments etc, but they might want to know how to run a classifier to produce a labelled passage, or what we're trying to do with our knowledge graph at a high level
This PR:
- spruces up the front-facing README with newcomers in mind
- moves our existing justfile command documentation to a new file in `docs/developers` (sidenote: should we be documenting more stuff in there? less? who is that dir for, and what do we think it should do for them?)

make the readme a bit more friendly for newcomers

---

flows/index.py

---
- Is a bugfix for the indexing code to ensure we no longer hit prefect api rate limits. 
We were doing the following:
```python 
index_by_s3
-> async run run_partial_updates_of_concepts_for_batch_flow_or_deployment 
-> async run run_partial_updates_of_concepts_for_batch 
-> async run run_partial_updates_of_concepts_for_document_passages 
-> async run partial_update_text_block
```
This meant that we were running a huge number of processes asynchronously, many of which were hitting the prefect api. We could have removed the flow decorator from some of the functions to reduce prefect api calls but I think at the moment it's better to just reduce the amount we're trying to do all at once. 
We can spun up n number of indexers in parallel by toggling the batch size so we …

Bugfix - indexing rate limits 

---

flows/index.py

---
- Catches raised exceptions, particularly when no passages are found for a document. 
- When we were running `run_partial_updates_of_concepts_for_batch` asynchronously the value errors that were thrown when there were no passages found for a document did not propagate and stop the program due to the use of the `asyncio.gather`. Now that we are awaiting the result the exception is being thrown and thus must be caught.
- I considered being tight on the exception handling and setting a ValueError, but then we might stop the entire program for another type of error and the prior solution didn't have granular exception handling so this is no step backwards.

Catching raised exceptions when no passages for a document.

---

flows/index.py

---
- Adds logging to the `run_partial_updates_of_concepts_for_batch_flow_or_deployment` function.
- This is in response to some undesired behaviour in the latest run where asynchronous running of deployments didn't go as planned. My theory is that we are exceeding the max limit of a parameter to pass into a flow in prefect: 
https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/2ad3e80b-ee0c-4841-8193-a450b50f9294?entity_id=e67b2924-9467-4b33-a3be-e5a3380fbcac

Additional logging to debug indexing flow

---

flows/index.py

---
- Removes the flow decorator from a function. 
- Below we are validating the size of the parameters before invoking a flow or deployment, thus this can't be a flow itself.

Removing flow decorator.

---

flows/index.py

---
- Ups the time out of the run deployment call to 1 hr as we were experiencing the awaitable cancelling / no longer waiting for a result and continuing on to the next loop.

Updating time out for run deployment.

---

flows/wikibase_to_s3.py
src/wikibase.py
tests/conftest.py

following https://github.com/climatepolicyradar/knowledge-graph/pull/281, adding this kwarg to our `get_concept` call should give us the complete ancestry for each concept object in s3. I'll follow up with a separate PR to propagate the values down the pipeline towards vespa, but this should _already_ be a helpful addition for the application team 🎉 
the last PR also included a stupid mistake re which fields we add the fetched relationships to! I've fixed that here.

include recursive_subconcept_of in objects persisted to s3

---

deployments.py
flows/data_backup.py
scripts/get_concept.py
scripts/push_to_argilla.py
src/argilla_v2.py
tests/test_argilla_v2.py

We want to follow the same pattern with Argilla that we did for Huggingface, and Wikibase, our other two external data stores in this repo, namely that each of them have a `<service_name>Session` class, which is responsible for all transactions between the data store and the KG repo. This PR refactors all of the argilla v2 code into the `ArgillaSession` class which follows this pattern.
It also readds the data-backup flow deployment, now that the bug of trying to initialise the argilla client before pulling the credentials from ssm is fixed, and client connection is more safely managed.

Refactor argilla v2 into `ArgillaSession`

---

flows/count_family_document_concepts.py

We're confident now, since it's been used for several weeks.

fix: Enable reporting for loading concepts counts

---

.github/workflows/bump.yml

This has a compromised GH Action[^1] that dumps secrets.
For now, this just disables the workflow from running, and then we can refactor it with an alternative approach.
This is the only use within our GitHub organisation[^2].
[^1]: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
[^2]: https://github.com/search?q=org%3Aclimatepolicyradar+uses%3A+tj-actions%2F&type=code

build: Disable running workflow

---

flows/index.py

---
- Is a refactor to update the naming of document id in the **_INDEXING_** pipeline to being file stem where applicable. 
- This is as we are referring to objects as documents ids when they are not which has lead to processing [issues](https://linear.app/climate-policy-radar/issue/POL-2385/classifiers-not-working-on-translated-documents#comment-a3d1103a). 
- Why use file stems? This is the attribute that is used in the `Path` object, e.g.:
```python
>>> Path("s3://..../file.json").stem
>>> "file"
```

Refactoring document id to file stem in the indexing pipeline

---

flows/inference.py
tests/flows/fixtures/PDF.document.0.1.json
tests/flows/test_inference.py

---
- Updates the inference pipeline to run on only english documents. 
- Notably we don't run inference on documents that have no language. 
- This is as there will be a corresponding translated document that has language english. 
- We don't wish to run inference and indexing on both and are preferring the english version.

Run inference on only english documents.

---

deployments.py
flows/boundary.py
flows/count_family_document_concepts.py
flows/deindex.py
flows/index.py
flows/utils.py
flows/wikibase_to_s3.py
tests/flows/conftest.py
tests/flows/test_boundary.py
tests/flows/test_count_family_document_concepts.py
tests/flows/test_deindex.py
tests/flows/test_index.py
tests/flows/test_utils.py
tests/flows/test_wikibase_to_s3.py

We now wipe the concepts from S3 (the CDN).
Along with this, we trigger the new de-indexing pipeline, to remove the concepts' inference and concepts counts objects, and labelled passages (spans) in Vespa.
TOWARDS PLA-469

feat: Clean-up and de-index concepts

---

scripts/clean_labelled_passages_directory.py

---
- Removes the loading of objects from s3 during labelled passage removal conditional. 
- This is as we don't need the content just the file name to drive the removal action. 
- Identified as being required as local run was taking a long time.

Removing json load from s3 for labelled passages.

---

flows/index.py

---
- Is a bug fix for a key error seen in staging related to empty metadata (e.g. no concepts). 
- This is as we have updated inference to now output labelled passages with no results. 
[prefect run](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/3164c898-19e2-4f1e-9a2a-555337e32780?entity_id=143073b1-3128-437e-882c-d9cd6e0706a2)
Example empty labelled pasasge: 
```json 
{"id": "0", "text": "Vintage 2018", "spans": [], "metadata": {}}, {"id": "1", "text": "Official Gazette of the Kingdom of the Netherlands", "spans": [], "metadata": {}}
```

Adding in a bug fix for the scenario when we have no concepts.

---

flows/inference.py
tests/flows/test_inference.py

I did an inference run[^1] and everything succeeded! jk, none that I sampled did. Similar to changes yesterday, this change surfaces failures for tasks.
[^1]: https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/9c17ae1c-a9b6-4fa6-b1c7-c6d7e6a61994?entity_id=f3afae10-f141-44ae-b969-ad695df5b74c

fix: Surface tasks failures in inference

---

.github/workflows/cd.yml
.github/workflows/ci.yml

I've found it slightly distasteful to have checks permanently skipped for PRs, as it makes it slightly less clear on PRs when looking at checks, and I think it's neater to explicitly have the dependency as "iff CI passes" checked as few times as possible, and at the highest level possible.
It's now possible to have cross-workflow dependencies[^1]!
[^1]: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run

build: Separate CI/CD

---

flows/boundary.py
flows/utils.py

We don't store the translated prefeix for the family document ID. Thus, strip it out.
I came across this when investigating a de-index pipeline run[^1].
Some time, we should add tests for the translation scenario.
[^1]: https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/226ea582-2bcc-465a-99be-e6a85005e1dc?entity_id=a2ec38ff-35eb-4fcf-9443-0cc3c3fc805d

fix: Use Vespa-friendly family document ID

---

flows/inference.py
tests/flows/test_inference.py

I found it odd that we'd allow this. If, at this level, of the pipeline we're trying to run inference we'd surely be expecting the document to exist.
Now we do!

refactor: Don't allow missing documents for inference

---

flows/inference.py
flows/utils.py
tests/flows/test_utils.py

---
Updates the KG pipelines to: 
- Remove non translated file stems if we find a translated one.
- This should reduce noise from trying to run inference on non-english documents as documents with no language or a non english language will have a relating translated one which we do present for inference. 
- Also integrates a bug fix for an error that was observed in [staging](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/1f494e56-d870-4cfe-b068-8b625e15a3de?entity_id=1f494e56-d870-4cfe-b068-8b625e15a3de). 
```shell
Failed due to a(n) AttributeError in the Prefect flow run. The error occurred because the 'FlowRun' object does not have an attribute 'flow_run_name', leading to a failure …
```

Bugfix: Reduce noise from non-english docs presented to inference

---

flows/boundary.py
flows/count_family_document_concepts.py
flows/deindex.py
flows/index.py
flows/inference.py
flows/utils.py
flows/wikibase_to_s3.py
scripts/cloud.py
scripts/infer.py
scripts/promote.py
scripts/update_classifier_spec.py
src/version.py
tests/flows/test_boundary.py
tests/flows/test_deindex.py
tests/flows/test_index.py
tests/flows/test_inference.py
tests/flows/test_utils.py
tests/scripts/test_update_classifier_spec.py
tests/test_evaluate.py
tests/test_infer.py
tests/test_promote.py

It's now strict on when this is allowed.
FIXES PLA-515

fix: Don't allow misleading `latest` version

---

flows/inference.py

text blocks are stored as type `TableCell`. These are 60% of all text blocks [[1](https://www.notion.so/climatepolicyradar/3-TableCells-eeeb3f4453744e5b8fd70d8f6a5adf3f)].
As a shortcut, we should skip running on these (although it wouldn't be a bad idea to run inference on them in the long run.

don't run on table cell

---

flows/inference.py

Reverts climatepolicyradar/knowledge-graph#348
Matyas pointed out that there is a lot of good content in these text blocks. Mark is hopeful that with all the other work around improving read/write times, reduced batch sizes, increased Vespa resources, not trying to run on every document at first, this would be insufficient.
It's something we can keep in our back pocket, and possibly apply per document.
I was very hasty in merging it in, as it immediately appealed to solving the load issue!
FIXES PLA-523

fix: Re-allow table cells

---

Dockerfile

---
- Is a bug fix for the docker build that was caused by an llm dependency group being present when it is not in the `pyproject.toml`. 
- Failed CI can be seen [here](https://github.com/climatepolicyradar/knowledge-graph/actions/runs/14469560735/job/40579978114).

Removing llm group from dockerfile.

---

flows/utils.py
tests/flows/test_utils.py

---
- Adds a fix for the slack notification. 
- Essentially the load method can either return the Slack webhook object or a coroutine and thus we need to handle the different scenarios. 
- A coroutine is returned if the async_load function is called which occurs when the object is instantiated within an async function like in the KG pipeline. 
- An example of the traceback that was seen can be seen in the related linear ticket.

Adding in a fix for the slack notification call.

---

flows/boundary.py
flows/utils.py
pyproject.toml
src/identifiers.py
tests/flows/test_boundary.py
tests/flows/test_deindex.py
tests/flows/test_index.py

Instead of doing 1 read per document passage, get the most possible at once.
It uses paging as well. If there's > max limit for 1 read, then it'll use paging to break up the text blocks, and do `n` reads, with the max limit each time.
**Validation**
FIXES PLA-520

refactor: Batch read document passages

---

flows/boundary.py
flows/count_family_document_concepts.py
flows/deindex.py
flows/index.py
pyproject.toml
tests/flows/conftest.py
tests/flows/test_boundary.py
tests/flows/test_deindex.py
tests/flows/test_index.py
tests/local_vespa/README.md

Instead of creating new connections every time we interact with Vespa, create a pool instead. This is intended to reduce the overhead of creating a new network connection and the Python objects. This would've had a larger effect when we were doing per-document passage read requests, but is still helpful.
**Testing**
Successful run: https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/92adf6f0-8547-4010-becf-3d6f695ec39f?entity_id=92adf6f0-8547-4010-becf-3d6f695ec39f
FIXES PLA-522

refactor: Use Vespa connection pool

---

flows/boundary.py
flows/index.py

This Pull Request:
---
Removes the parent timeout from the indexing deployment/flow.
Keeps the timeout on the run_partial_updates_of_concepts_for_batch flow in place. This timeout continues to protect against spawning too many child indexing jobs.
Reason for Change:
This adjustment is a response to a timeout encountered during [this run](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/8580f2ce-a5bb-46dd-810d-39685ef14f46?entity_id=8580f2ce-a5bb-46dd-810d-39685ef14f46&state=cancelled&state=cancelling&state=completed&state=crashed&state=failed&state=paused&state=pending&state=running&state=scheduled&entity=flowRuns&entity=taskRuns&entity=events&entity=logs&entity=artifacts), where the run exceeded the …

Removing the parent timeout for indexing.

---

deployments.py

---
- Is a bug fix in response to a failing [deployment](https://github.com/climatepolicyradar/knowledge-graph/actions/runs/14856928830/job/41712382062) to staging due to invalid import paths. 
- Rather than having a removal and update deployment we now handle both within the `run_partial_updates_of_concepts_for_document_passages` deployment. 
- Now passing prefect staging [deployment](https://github.com/climatepolicyradar/knowledge-graph/actions/runs/14857371668/job/41713789188).

Bugfix: Failing CD due to deployment import paths 

---

flows/boundary.py
tests/flows/test_boundary.py

---
- Is a bug fix for failed queries during indexing raised during this prefect [run](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/c8e7199e-9c54-43f3-8653-62297ad0e4c9?entity_id=c8e7199e-9c54-43f3-8653-62297ad0e4c9&state=cancelled&state=cancelling&state=completed&state=crashed&state=failed&state=paused&state=pending&state=running&state=scheduled&entity=flowRuns&entity=taskRuns&entity=events&entity=logs&entity=artifacts). 
- The proposed fix is an update to how many text block ids we append to the equiv operator query.
- Validated what the limit should be using the added test by incrementally reducing the limit. 
- Staging [run](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b1 …

Bugfix: Query too long 

---

Dockerfile

This was missed previously. The project is currently on `3.3.11`, but Prefect doesn't publish tags for every version, it seems[^1][^2].
Thought it's better to at least get onto `v3` at least.
**Testing**
Deployed to [staging](https://github.com/climatepolicyradar/knowledge-graph/actions/runs/14888606649/job/41814768981) and ran [a flow successfully](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/14bf0856-08b8-4c6e-8bd4-350505ed5071?entity_id=14bf0856-08b8-4c6e-8bd4-350505ed5071).
FIXES PLA-468
[^1]: https://hub.docker.com/r/prefecthq/prefect/tags?name=3.3.11-python3.10
[^1]: https://hub.docker.com/r/prefecthq/prefect/tags?name=3.3.7-python3.10

fix(flows): Use Prefect v3 image

---

poetry.lock

When building the image, I noticed this warning:
```
12.48 Warning: The file chosen for install of multidict 6.3.2 (multidict-6.3.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl) is yanked. Reason for being yanked: Memory leak: https://github.com/aio-libs/multidict/issues/1131#issuecomment-2787514071
```
Poetry also warned about it:
```
Warning: The locked version 6.3.2 for multidict is a yanked version. Reason for being yanked: Memory leak: https://github.com/aio-libs/multidict/issues/1131#issuecomment-2787514071
```
It now is a version that uses a fixed[1][2] version of multidict.
[^1]: https://github.com/aio-libs/multidict/issues/1131#issuecomment-2787514071
[^2]: https://github.com/aio-libs/aiohttp/blob/1acf8c94e7b5ad7d1a2ce6cfec0937abbe43a6eb/requirements/multidict.txt# …

fix: Use non-memory leaking aiohttp

---

.github/workflows/cd.yml

Whenever I see that CD failed, it causes me a tiny bit of stress and
use my time, so here we go.

build: Disable deploying docs

---

pyproject.toml

We've had a warning for a while:
```
poetry run pytest --disable-pytest-warnings --color=yes -v -m 'not flaky_on_ci and not transformers' --ignore tests/test_argilla_v2.py --ignore tests/test_task_distribution.py
12
/home/runner/.cache/pypoetry/virtualenvs/knowledge-graph-67_EgitM-py3.10/lib/python3.10/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
13
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop
scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", …
```

test: Set pytest-asyncio scope

---

scripts/update_classifier_spec.py
tests/scripts/test_update_classifier_spec.py

Until now, we were effectively relying on the order of model artifacts, to determine what the _right_ verion is to use. The implicit ordering reliance is for newest to oldest.
As part of promotion, the AWS env. is attached to a model version, to indicate this _the_ one to use by default.
This change now looks for the model version that has the appropriate AWS env. label, that indicates primariness.
FIXES PLA-584

fix: Use the primary model version, not the latest

---

scripts/do_classifier_specs_have_results.py
tests/scripts/test_do_classifier_specs_have_results.py

This builds on the existing script that checks the output of inference flows to confirm classifiers have actually run. The original checks for files under the classifier prefix and runs sequentially. This sets up the script to run in parallel, and adds the option to write out the file ids (these can then be used for finding gaps in the results).
As a bonus I also added tests and reworked the input aiming to require less typing.

Make it easier to audit gaps in inference results

---

flows/inference.py

This follows hitting a number of timeouts when running inference. I doubt this will be the final value for these, but will make it easier to run larger classifiers in the immediate future.

Increase the timeout for inference

---

flows/boundary.py
tests/flows/test_deindex.py
tests/flows/test_index.py

It's still not happy that the Prefect logger isn't available due to it not being in a flow or task[^1]:
```
2025-05-06T11:15:53.190Z File "/opt/prefect/knowledge-graph/flows/boundary.py", line 1170, in _vespa_response_handler_cb_with_state
2025-05-06T11:15:53.190Z vespa_response_handler_cb(
2025-05-06T11:15:53.190Z File "/opt/prefect/knowledge-graph/flows/boundary.py", line 1217, in update_feed_result_callback
2025-05-06T11:15:53.190Z logger = get_run_logger()
2025-05-06T11:15:53.190Z File "/usr/local/lib/python3.10/site-packages/prefect/logging/loggers.py", line 155, in get_run_logger
2025-05-06T11:15:53.190Z raise MissingContextError("There is no active flow or task run context.")
2025-05-06T11:15:53.190Z prefect.exceptions.MissingContextError: There is no active flow or task run …
```

fix: Don't pass a logger and print instead

---

flows/boundary.py
pyproject.toml

Whilst we don't have reproducible steps for the memory issue, and thus I'm not certain if this will fix the issue, it has at least led me to identify this issue.
While list operations are atomic[^1], I have some doubts about relying on the bytecode ordering, and they do suggest to use a mutex if in doubt, so here's a mutex in the form of a lock.
There will be _a_ performance hit, though around that area, the slowest code would be the network call, and updating a list and a counter should be quick.
TOWARS PLA-573
[^1]: https://docs.python.org/3/faq/library.html#what-kinds-of-global-value-mutation-are-thread-safe

fix: Safely access shared data across Vespa feed callbacks

---

flows/inference.py

Hopefully temporarily because i'd like to have a better solution here, but these are currently blocking target inference, and prefect didnt seem to change its config when I increased the value, so they don't seem to behave very well. Even if they did, the documentation states that: "Flow execution may continue until the next task is called" https://docs.prefect.io/v3/develop/write-flows#:~:text=ThreadPoolTaskRunner%20is%20used.-,timeout_seconds,-An%20optional%20number
Meaning they don't do a hard stop currently anyway

Disable timeouts for inference

---

flows/boundary.py
flows/index.py

See individual commits about the ways this resolves logging issues. One of which led to an actual failure:
- Fix logging around the `s3_accessor`
I was curious why "s3_prefixes" didnt appear in the logs, and after
taking a closer look at what that log line was doing realised theres a
very good chance its failing to log out a gigantic log object. This
would also make sense of why the open telemetry failure occured here as
well as the underlying state update error due to request size
I also moved the logic for what to log out of the main function for
neatness reasons
- Log print statements
Prefect was missing log statements that where found in ecs. This is due
to the function `s3_paths_or_s3_prefixes` having print statements rather
then use logging. Elsewhere we have adopted print …

Fix logging issues in indexing

---

flows/boundary.py

We found examples of our query returning too few passages. After some investigation it turned out to be normal for inference to have less, but the other way around is a genuine problem that we want to surface right away

Make check specific for actual issues

---

flows/boundary.py

Because of the way vespa works with querying we where losing passages in the response. This is because by default the way vespa handles searches across nodes and pools the results is optimised for performance not accuracy.
In our case here, we kinda really need accuracy and this can be changed by overriding the default "precision" parameter in the grouping query.
See:
- https://docs.vespa.ai/en/reference/grouping-syntax.html#precision
- https://docs.vespa.ai/en/grouping.html#performance-and-correctness

Add precision to grouped query

---

.github/workflows/cd.yml

Deploying should either be automatic (via the CI work flow completing) or via a manual trigger. For the former, we had the trigger, but we weren't checking if the completed workflow was a success completion, as opposed to something else like a failure completion.

ci: Check if the `workflow_run` completion was a success

---

flows/inference.py
tests/flows/test_inference.py

---
- Filters out sabin documents from inference only (if they aren't in inference outputs they won't be presented to indexing). 
- Using the file stem to filter out the documents and ensuring we aren't case sensitive so we're resilient to minor upstream naming changes. 
- The alternative option I could see to using the file stem was to use the `source` field in the `document_metadata` of the parser outputs. However this would require reading the file from s3 and the document metadata field is just typed as a dict so this method was not deemed ideal. See example below:

Filtering out sabin documents from inference.

---

scripts/do_outputs_align_for_a_document.py

Adds a script that compares: vespa documents, vespa passages & inference outputs printing a table of the count for each per concept. This is intended as a quick way of confirming consistency across sources
Running example:
```
python scripts/do_outputs_align_for_a_document.py \
"CCLW.executive.11060.6361" \
staging \
<staging_s3_bucket>
```
Output example:

Add discrepency auditing script

---

.gitattributes
.github/workflows/ci.yml
README.md
flows/boundary.py
justfile
pyproject.toml
tests/flows/conftest.py
tests/flows/fixtures/labelled_passages/Q218/v4/UNFCCC.party.309.0_translated_en.json
tests/flows/test_index.py
tests/local_vespa/local_vespa.just
tests/local_vespa/test_documents/family_document_UNFCCC.party.309.0.json

Huge documents simply are a thing, and thus we should have better testing around them. This also can help with benchmarking. This test whilst not calling the function directly that uses continuation tokens, calls it as part of a higher function.
`tests/local_vespa/test_documents/document_passage_UNFCCC.party.309.0.json` has 50,024 document passages in it. We wanted at least > 50,000. This data was pulled from Vespa (staging).
Doing the document passages feed took 18s once. The test took 48s once. I think this is fine to have run by default on CI.
FIXES PLA-590

test: Add very large test for indexing a document

---

flows/boundary.py
flows/count_family_document_concepts.py
scripts/do_classifier_specs_have_results.py
scripts/do_outputs_align_for_a_document.py

This came out of me, in a code review, asking for more of these `TypeAlias`s to be added, and wondering if they're effective for static checks, and not just making function signatures more human readable.
Turns out, they weren't good for the former[^1]. There is a little boilerplate with having to instantiate the type, but alas, I feel the potential type checker warnings is worth it. We'll see though, and maybe there's a way to avoid this.
[^1]: https://climate-policy-radar.slack.com/archives/C078S46DJFP/p1748337885539729

refactor: Use stricter type hinting for `str`s and constants

---

flows/boundary.py
pyproject.toml
tests/flows/fixtures/labelled_passages/Q218/v4/UNFCCC.party.309.0_translated_en.json
tests/flows/test_boundary.py
tests/flows/test_deindex.py
tests/flows/test_index.py

This takes us back to a time before we [tried to use](https://github.com/climatepolicyradar/knowledge-graph/pull/368) `pyvespa` for working through all our updates operations.
It was way too far to do a simple revert, so I've written this based on what was before that PR, and where we've gotten to.
Effectively, no tests were needed to be updated. This is a good thing! It indicates that the functionality/effects weren't changed.
FIXES PLA-603

refactor: Explicitly control updating document passages

---

flows/boundary.py
flows/index.py
flows/utils.py
pyproject.toml
tests/flows/test_boundary.py

A batch of tasks means that the batch has to wait until all tasks finish, before starting the next batch. That means the coroutines are _inflexible_.
Instead, use a queue AKA lock AKA semaphore, so that the concurrency is managed by there being _space_ in the semaphore. E.g. a semaphore of 8 means that there's 8 concurrent tasks. A task blocks until it acquires a lock, from the semaphore.
TOWARDS PLA-615

refactor: Allow flexible async coroutines

---

deployments.py

Think I was rushing a bit and had confused the names of the deployment, I also managed to specify an invalid config as the cpus are supposed to scale with the memory. Based on the aws documentation this should work: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html
Ironically the aggregator did work when I ran it after this change, I suppose there must be some transcience dependant on which documents are run in parrelel

fix: apply valid memory to correct deployment

---

deployments.py

This was already fixed in 805788d41ab7046919a9108adc9848d5eaf1a691 but somehow made its way back in

fix: remove invalid memory value

---

flows/aggregate_inference_results.py
flows/boundary.py
flows/utils.py
tests/flows/test_aggregate_inference_results.py

This adds a prefix alongside the run identifiers that holds all of the latest  aggregated results.
The idea here is to have all the latest ran aggregations compiled in a single place. Previously, all the documents to be drawn on for indexing would need to be within a single run identifier. Most of the time this is really useful and lets us only run on what has just been completed. But there are also times when we need to rerun on everything, or when we want to review what the current state should be. In this case it helps to also maintain all of the last aggregated documents. Another key benefit is for analytics, we can review all aggregations in one go, now in s3, later also in the data lake.
We previously had some bad experiences with using `latest` with models, but I do think this is …

Support both incremental and historical runs

---

justfile
scripts/audit/do_outputs_align_for_a_document.py

Since merging 9f07055daab2f0656760fc0a0b8e88526cde5161 we can now review "latest" for this by default

feat: no longer require run identifier for audits

---

flows/aggregate_inference_results.py
flows/boundary.py
poetry.lock
pyproject.toml
tests/flows/conftest.py
tests/flows/test_aggregate_inference_results.py

This draws on the aioboto3, a wrapper for boto that runs aws interactions async. The refactor is minimal but I've only applied this to the aggregator for now to air out any strangeness. If this works well we should roll it out as standard elsewhere.

refactor: Use async calls for aggregator s3 interactions

---

flows/index_from_aggregate_results.py
pyproject.toml

From the discussion in Slack (see: issue), we're reducing the number of Prefect calls via removing flow/task approaches.
This is to reduce the number of Prefect API calls so we're less likely to be rate-limited. The downside being that we lose observability.
Based on Prefect[^1], this is always being shown as a success state. This is misleading to us when evaluating the run. It should appropriately be a failed state too.
This begs the question of, are straying too far from the light of Prefect, and shouldn't be passing data in a failed flow run state?
FIXES PLA-640
[^1]: https://docs.prefect.io/v3/develop/manage-states#manage-states

fix: Representing indexing all as appropriate Prefect state

---

flows/index_from_aggregate_results.py
pyproject.toml

As per our usual patterns. For the sake of small code changes and concurrent safety, I wrapped the I/O call as the one thing that waits on the semaphore.
FIXES PLA-639

refactor: Add concurrency for indexing document passages

---

flows/aggregate_inference_results.py
pyproject.toml
tests/flows/test_aggregate_inference_results.py

I saw this a lot[^1][^2] and it created a lot of noise, and may also cause  actual problems. I don't think the latter would be true though, as we don't use cached results, explicitly at least.
The session was successfully passed to the task, and used within it. E.g. you can see the 404s for objects not existing. It doesn't show up in the args though in Prefect's webapp.
**Test**
- https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/068500ad-4c45-7734-8000-d58eb360ffef?entity_id=068500b4-27b2-723d-8000-0b5cb49b3953 — Ran went okay without the cache function error.
TOWARDS PLA-658
[^1]:
```
Error encountered when computing cache key - result will not be persisted.
Traceback (most recent call last):
File …
```

fix: Make task hashable

---

flows/inference.py
tests/flows/test_inference.py

---
- Is an update to the KG inference pipeline to no longer run inference on html documents with no valid text as these aren't indexed into vespa so passages won't exist.
- We also won't see the benefit of this until we rerun inference so we will still see some `ValueErrors` until then. 
_Note: Lot's of explanation on the linked linear ticket._

Don't run inference on html documents with invalid text 

---

flows/aggregate_inference_results.py
flows/index_from_aggregate_results.py
flows/result.py
pyproject.toml
tests/flows/test_index_from_aggregate_results.py

Task mapping has worked well recently in inference aggregation. It's used here as one way of getting better observability, as it's unclear right now which `index_all` runs fail.
Along with this, it's unclear which Vespa updates go wrong, so this improves that, and also there's additional logging to understand the updates.
**Test**
Here's what the Vespa updates print as:
```
doing update data at path /document/v1/doc_search/document_passage/docid/CCLW.executive.10014.4470.175 with fields {'concepts': []}
doing update data at path /document/v1/doc_search/document_passage/docid/CCLW.executive.10014.4470.766 with fields {'concepts': []}
doing update data at path /document/v1/doc_search/document_passage/docid/CCLW.executive.10014.4470.1431 with fields {'concepts': []}
doing update data at path …
```

refactor: Use task mapping and log Vespa updates

---

flows/aggregate_inference_results.py
flows/index_from_aggregate_results.py
pyproject.toml

This is a regression from my recent refactoring.
The lack of `__str__` meant that Prefect had `"message": "Task run encountered an exception Fault: ",`, which is unhelpful. I had seen this before for `AggregationFailure`s, so I've fixed that too.
**Test**
[Flow run](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/0685abf6-4890-7132-8000-91e173780f61?g_range=%7B%22type%22%3A%22span%22%2C%22seconds%22%3A-604800%7D&entity_id=0685abfe-3dc4-7fe4-8000-6dc0ac480db8&state=failed&entity=flowRuns&entity=taskRuns&entity=events&entity=logs&entity=artifacts)
```
"message": "Task run encountered an exception Fault: Unexpected exception during document indexing | metadata: {\"document_stem\": …
```

fix: Use correct `Fault` metadata field and make them printable too

---

scripts/build_dataset/02_download_litigation.py
scripts/build_dataset/05_add_geography.py
scripts/push_to_argilla.py
scripts/upload_targets_data.py
src/classifier/classifier.py
src/classifier/embedding.py
src/classifier/llm.py
src/concept.py
src/identifiers.py
src/labelled_passage.py
src/span.py
src/version.py
src/wikibase.py
tests/test_classifier.py
tests/test_identifiers.py

Adding this PR to kick things off, with the intention to hand over the rest of the work on [PLA-557](https://linear.app/climate-policy-radar/issue/PLA-557/overhaul-of-model-id-to-add-lineage-tracking) to @climatepolicyradar/deng, who will do a much better job than me at the rest of the implementation.
This PR adds a new `Identifier` class, whose `Identifier.generate()` supersedes the `generate_identifier` function with much nicer structures for validation and testing etc. There's still more work to do here (broken down in the top-level ticket) but I hope sets some sort of direction/intent for the subsequent bits of work 🙇‍♂️

Add a new dedicated Identifier class

---

src/classifier/bert_based.py
src/classifier/classifier.py
src/classifier/embedding.py
src/classifier/keyword.py
src/classifier/llm.py
src/classifier/rules_based.py
src/classifier/targets.py
tests/test_classifier_mixins.py

Kicked off by [this conversation](https://github.com/climatepolicyradar/architecture-hub/pull/31#discussion_r2168576236)
> I'd like to be able to mark some classifiers as having a particular characteristic, eg an `LLMClassifier` and a KeywordClassifier and a `RulesBasedClassifier` should all be instances of a `ZeroShotClassifier`, and a `TargetsClassifier` and a `BertBasedClassifier` should be instances of a `ClassifierWhichNeedsToRunInferenceOnAGPU`. Maybe that's set via a mixin, or through some other sort of superclass magic 🤔
Turns out that implementing this via a couple of mixins was very easy! We can now run simple checks like
```py
concept = wikibase.get_concept("Q123")
classifier = ClassifierFactory.create(concept)
if not isinstance(classifier, ZeroShotClassifier): …
```

Add mixins for high-level classifier attributes

---

deployments.py
flows/aggregate_inference_results.py
flows/index_from_aggregate_results.py
flows/utils.py
pyproject.toml
tests/flows/conftest.py
tests/flows/test_aggregate_inference_results.py
tests/flows/test_index_from_aggregate_results.py

Similar to other pipelines, run inference aggregation multi-host.
I've taken this opportunity to find the re-usable pattern here. It is in effect, a faux Prefect task runner. This gives a single function to call that behind-the-scenes, uses our `run_deployment` + semaphore + results handling (separate successes and failures) pattern.
**Test**
I did a [flow run](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/068654e3-7283-74d9-8000-103eb5bfd237?entity_id=068654ea-7470-75f4-8000-43d606a19ffc&state=failed&entity=flowRuns&entity=taskRuns&entity=events&entity=logs&entity=artifacts), the made sure that it would only 2 run some batches first, to the max of the semaphore counter, and of the parameterised batch …

refactor: Run inference aggregation as multi-host

---

flows/aggregate_inference_results.py
flows/index_from_aggregate_results.py
flows/utils.py
tests/flows/test_aggregate_inference_results.py
tests/flows/test_utils.py

---
- Refactors the use of `DocumentId` to `DocumentStem` in aggregate inference results KG pipeline. 
- This is required as in the labelled passages pipeline we read in document stems and persist this to the output.
- This means that we have labelled passages with the translated suffix and thus cannot be read via document id. 
- Discussion on any splash damage of the misuse of document ids has been listed on the ticket.

Refactor DocumentId to DocumentStem in aggregate inference results pipeline

---

flows/index_from_aggregate_results.py

---
- Is a bugfix for the indexing from aggregated inference results KG pipeline. 
- The `indexer_document_passages_concurrency_limit` parameter was declared in the `run_indexing_from_aggregate_results` but then was not passed through in to the sub deployments. 
- Then within the sub deployment we were using the `indexer_max_vespa_connections` parameter where we should have been using the passage level concurrency parameter.

Passing through the passage concurrency limit correctly.

---

flows/classifier_specs/spec_interface.py
flows/classifier_specs/v2/sandbox.yaml
src/identifiers.py
tests/flows/classifier_specs/test_spec_interface.py

We are moving to having specs with more data included in them. This starts an interface for working with these new file structures. There was plenty of code existing spread out that interfaces with the old files, this begins to consolidate that for the new files.
More work will be needed to update before and after this point in the lifecycle (i.e. training, inference, etc). The basic reading of these files seemed like a good place to start as these tie everything else together.

feat: spec reader interface for specs with more data

---

flows/classifier_specs/spec_interface.py
src/version.py

This was missed from a previous PR after it was suggested about these specs.

refac: Use `Version` for `wandb_registry_version`

---

flows/utils.py
tests/flows/test_utils.py

Use the Prefect [progress kind of artifact](https://docs.prefect.io/v3/how-to-guides/workflows/artifacts#create-progress-artifacts) for places where it either takes generally a while and/or there's a lot of things to enumerate through.
I've tried to make it as _for free_ as possible, so it's in the sub-flow mapping function, and I've created a gather equivalent.
More can be done as we go along in the repository.
**Demo**
Flow run: https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/06881402-67a0-797b-8000-7ccc08a829e7
1. 0%
2. 50%
3. 100%
FIXES PLA-610

feat: Add progress reporting

---

scripts/predict.py
scripts/train.py
scripts/utils.py
tests/test_train.py

This switches training to run using the id of a classifier rather than its name. To make this easier to update I also did some more general refactoring of the train script, if needed these changes can be seen progressively by clicking through the commits. The actual core change, where we switch from name to ids is in efec302b504418bcc9df45b67623ac2c29430a61
Extra things to note:
- We do still use the wandb version as the local & s3 file name for now, although I deliberated wether to or not as it should always be v0 in this way of doing things, but I think in practice its easier to hang on to it for now so we can see explicitly if the assumptions around it becoming irrelevant are wrong
- The context of what class is being used for a classifier (its name) is moved to metadata as it still …

Refactor training to use classifier ID instead of name

---

scripts/train.py
tests/test_train.py

The model connection between artifacts and s3 stores is a one to one, which means unless we revisit this our models will all have a coupling with a specific environment. This is now the only tangible difference between versions of a model. This adds the env as an alias to each model. We already do this in the registry at promotion, but as models stay in their env it makes sense to do it in training too
The benefits to this is are:
* Clarity for humans when reviewing wandb which model is for which environment
* Easily identify the environment for a model programmatically in a more dynamic way.

feat: include env in the wandb `artifact` alias

---

.github/workflows/stale.yml

We have a number of stale PRs across our codebase, I'd like to find a way of keeping these cleaned up and am interested in trying this out here in the knowledge graph repo first. I've taken 40 days as the amount of time before a PR should actually be closed for now. My view is that after this time the PR is probably never going to be merged because the rest of the repo has changed, so it either should have gotten merged earlier or needs to be reopened. The specific timing could be adjusted though.
Note that for exceptions the label `stale-exempt` can be added to a PR.
See for reference: https://github.com/actions/stale

ci: add stale pr detection

---

tests/conftest.py
tests/flows/conftest.py

When running `pytest tests/test_promote.py` with this line tests take 17.6 seconds. Removing it and they take 1.2 seconds. All of our prefect test flows live in `flows/`, which has its own conftest file that spins up this prefect server. Meaning any time we are running just on a module outside this repo we are losing ~15 seconds per test run for no reason.
I don't expect this to have any benefit in ci, but when running non-flow tests locally this should save time. Note that if we ever have flows outside of the flow directory we'll now need to ensure they have the harness.

test: scope test prefect server to test flows

---

scripts/deploy.py
scripts/promote.py
tests/test_promote.py

Switches promote to use classifier ID. For this
* The project model now gets looked up using the `classifier_id` argument (which has replaced `classifier`).
* The version is no longer a necessary parameter so it is removed and the id:env is used to look up the classifier instead.
* The lookup of existing collection artifacts is revised to use the artifact id instead of just the version
Interestingly, it looks like we had a bug in the way we looked up existing registry items, as the code had some confusion about which version was being used (project artifact version versus collection artifact version, which are not in sync). This has been resolved by using the `classifier_id` to make sure we are actually looking up the right classifier.

Update promote script to use classifier ID

---

flows/classifier_specs/spec_interface.py
scripts/promote.py
scripts/utils.py
src/classifier/bert_based.py
src/classifier/classifier.py
src/classifier/embedding.py
src/classifier/keyword.py
src/classifier/keyword_expansion.py
src/classifier/large_language_model.py
src/classifier/rules_based.py
src/classifier/stemmed_keyword.py
src/classifier/targets.py
src/identifiers.py
tests/flows/classifier_specs/test_spec_interface.py
tests/test_classifier.py
tests/test_classifier_mixins.py
tests/test_promote.py

When Identifier is a ClassifierID, its nice to clearly show this is the case. For this a new model is used that inherits from Identifier and then applied wherever the `Identifier` is being used as a `ClassifierID`.
[This follows up on a discussion here](https://github.com/climatepolicyradar/knowledge-graph/pull/574#discussion_r2256643258).
For future consideration, Identifer is also used for other items such as concepts, maybe we'd like the same logic applying? I'm going to leave this for someone else / later though

refactor: add ClassifierID wrapper for typing clarity

---

docs/docs/developers/justfile.md
scripts/README.md
scripts/demote.py
scripts/promote.py

There are more pieces of the model lifecycle that need updating but this follows a skim over the docs for what has changed so far and updates them.
Following a request for more documentation [here](https://github.com/climatepolicyradar/knowledge-graph/pull/574#pullrequestreview-3091805133), more should come as I go though

docs: Update documentation following id/version changes

---

src/wikibase.py

---
- Updates the wikibase class to use the default time out when running `_get_all_redirects`. 
- This is as during a local run of `just train` this request was timing out. The addition of the timeout resulted in success. 
```shell
poetry run train --wikibase-id Q1651
```

Use the default time out when retrieving redirects.

---

flows/full_pipeline.py

If inference entirely failed, don't simply return, as it gives the _full
pipeline_ and overall succeeded state, which is incorrect.
FIXES PLA-788

fix: Surface total failure of inference

---

static_sites/vibe_check/__main__.py

From ticket PLA-791: https://linear.app/climate-policy-radar/issue/PLA-791/support-vibe-checker
Updates the vibe checker to recursively include subconcepts and their labels, bringing it to parity with the train script. 
I do not have the knowledge-graph repo flows running locally right now, which means I cannot test this change locally. But it's a small change and well-evidenced so I'm keen to (in)validate the hypothesis before rabbit holing on local setup for hours. 
The vibe checker static site was only highlighting parent concepts (e.g., "solar energy") but not their subconcepts (e.g., "photovoltaic", "solar thermal", "concentrated solar power"), even though the trained classifiers include subconcept labels.
The wikibase get_concept method has parameters for …

Fix: Add recursive subconcept and alias parameters to vibe checker

---

automations.py

---
- Adds an automation for triggering the `full_pipeline` when the s3 backup is run. 
- Currently disabled until we fix the targets classifiers.

Feat: Run full pipeline on new documents

---

deployments.py

CD failed[^1], as `coiled-prod` was used instead of the correct `coiled-production` work pool name.
From some ADR, we decided on using `production` over `prod`.
I did consider handling this on the enum. It didn't seem like the right place, or not elegant, at least. I may come back to that.
Could the `name` attribute be used everywhere? I don't think so. It's a hack, so we don't want to encourage it.
TOWARDS PLA-759
[^1]: https://github.com/climatepolicyradar/knowledge-graph/actions/runs/16970954247/job/48107589223

fix: Use latest AWS environment name

---

static_sites/vibe_check/config.yml

Accidentally added the wrong concept ID for fossil fuel industry workers.

Corrected concept ID for Q1799

---

.github/workflows/ci.yml
Dockerfile
justfile
pyproject.toml
uv.lock

This has arisen post-migrating to uv with Python 3.12, utilising a GH cache for the images.
- Removing unused software (available space before 27G, after: 44G). This is done via background jobs, to significantly speed it up—from a few minutes to near instantaneous
- Don't install Python and uv outside of the Docker image
- Don't copy everything carte blanche
- Let building start immediately, since it's the longest job to run
- Do more post-build checks
**Test**
Built successfully: https://github.com/climatepolicyradar/knowledge-graph/actions/runs/17066912735/job/48386151210?pr=610. There's been others after this too.
I've cleaned out our [caches](https://github.com/climatepolicyradar/knowledge-graph/actions/caches) (`$ gh cache list`):
I'm not sure if the loading of the cache contributed …

ci: Avail space for Docker image building

---

.github/workflows/stale.yml

Looks like this is working! [Example PR marked as stale](https://github.com/climatepolicyradar/knowledge-graph/pull/369#issuecomment-3173910583), when checking that comment I realised this variable was mistyped.

fix: typo for stale workflow env variable

---

deployments.py

--- 
- Is a bug fix for the SIGKILL (memory error) being experienced in the inference stage.
- The bug is that providing an empty dictionary to the `create_deployment` function is resulting in the `DEFAULT_FLOW_VARIABLES` not being set and thus the default job variables having very low mem / cpu. 
- This can be validated with some code below as well as these default job [variables](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/deployments/deployment/99479d91-159a-4b09-95b4-0fef97d98936?tab=Configuration) on prod: 
```python
from typing import Any
def my(x: Any | None = {"the": "default"}):
print(x)
my()
my(x={})
``` 
- Deployed this branch to staging and observed the default job configuration …

Bugfix for default flow variables not being passed in to inference deployment.

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/prefect_deploy.yml
Dockerfile
pyproject.toml
uv.lock

We _fixed_ this yesterday, and immediately had it again. We had a cache of ~143GB! We also don't have cache cleanup.
**CI**
Scrap the separate build job. Caching via the GHA was being tedious, with the limitations of scoping. Building was happening a 2nd time in deploying. 
Previously, we didn't have any building, let alone caching, anyway! So this is still an improvement. Instead, rely upon the deployment to sandbox.
**CD**
We were caching in GHA, even though we use ECR. Instead, now cache _to_ and _from_ ECR[^2] (as opposed to, per environment). A `buildcache` tag is used, as is convention[^1].
This helps prevent cache explosion in GitHub and ideally helps speed up building and pushing to ECR, for CD. Along with this, I've added tags for SHA and `latest`, which can be helpful for …

ci: Stop Docker cache explosion

---

.pre-commit-config.yaml
README.md
automations.py
docs/docs/developers/environment-variables.md
docs/docs/index.md
docs/docs/users/hierarchy-heuristics.md
flows/boundary.py
flows/utils.py
pyproject.toml
scripts/demote.py
scripts/evaluate.py
scripts/promote.py
scripts/upload_targets_data.py
tests/flows/test_boundary.py
uv.lock

This was prompted by a spelling mistake of mine almost slipping through today. It can auto-fix spelling mistakes too, which is how all of these corrections came about, by running `$ just lint-all`.
I've used [typos](https://github.com/crate-ci/typos/) for a while personally, to great success, via the CLI, LSP, and in other repositories. It's fined for spelling within software.
**Appendix**
- I've updated all pre-commit hooks too.
- Add missing dependency: As surfaced by pyright.
- Migrated to the new name for `ruff-check`.

ci: Add checks, and fixes, for spelling

---

flows/utils.py
tests/flows/conftest.py
tests/flows/test_utils.py

This makes them a lot faster to parse, and overall easier to read, IMO.
I wanted to experiment with the Slack Prefect Blocks too. Unsurprisingly, they're very thin wrappers. I reached into the client, as they do, so I could get access to the result.
**Test**
[_Before_](https://climate-policy-radar.slack.com/archives/C07695T6J75/p1755784532994009)
[_After_](https://climate-policy-radar.slack.com/archives/C07695T6J75/p1755799486973789)

refactor: Prettify the Slack alerts

---

flows/aggregate.py
tests/flows/test_aggregate.py

---
- Is a bug fix for an intermittent error that was seen within the knowledge graph `full-pipeline`. 
- Logs of the error can be seen [here](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/task-run/0198e653-78b4-73ba-98a2-a83a3546b865/logs). 
> got Future attached to a different loop
- I believe the issue is that when we submit `process_document` tasks they may be submitted to a different thread than the `aggregate_batch_of_documents` flow. 
- `aioboto3.Session` is created inside the `aggregate_batch_of_documents` flow, and passed into the `process_document` tasks which are then run asynchronously. The session is not thread safe which I believe is causing the error should the process document …

Creating aioboto3 session within process_document function.

---

.github/workflows/ci.yml
justfile
pyproject.toml
src/classifier/stemmed_keyword.py
tests/flows/test_utils.py
tests/test_classifier.py
uv.lock

This uses the well-known pytest-xdist to run tests concurrently. The logical cores, vs physical cores, was chosen.
The bottleneck are the Vespa tests. We'll need to make those concurrent-safe eventually. I tested with using `testcontainers`, and had some success. I'm leaving it out for now, as it still needs work.
Still, this makes it faster overall, and, lets people iterate faster locally.
**Benchmark**
[_Before_
](https://github.com/climatepolicyradar/knowledge-graph/actions/runs/17136655410?pr=605)
[_After_](https://github.com/climatepolicyradar/knowledge-graph/actions/runs/17139071235)
**Appendix**
- Removed the unused `slow` marker
- Separated again, the transformers installation, to make linting faster, so it doesn't install so much
- I added a group so far just for the classifier` …

test: Run concurrently

---

flows/utils.py
tests/flows/conftest.py

I fixed an issue I introduced when making the notification pretty.
**Test**
```python
import asyncio
from prefect import flow
from flows.utils import SlackNotify
@flow(
log_prints=True,
on_failure=[SlackNotify.message],
on_crashed=[SlackNotify.message],
on_completion=[SlackNotify.message],
)
async def main():
pass
if __name__ == "__main__":
asyncio.run(main())
```
DEPENDS ON https://github.com/climatepolicyradar/orchestrator/pull/245
FIXES PLA-806

refactor: Allow all AWS environments to send Slack notifications

---

scripts/update_classifier_spec.py

When serialising the `run_only_on` and `compute_environment` fields, where causing warnings to be emitted:
```
PydanticSerializationUnexpectedValue(Expected `ComputeEnvironment` -
serialized value may not be as expected [input_value={'gpu': True},
input_type=dict])
```
```
PydanticSerializationUnexpectedValue(Expected `enum` - serialized value
may not be as expected [input_value='sabin', input_type=str])
```
This is resolved by refactoring how the model is built in the refresh so the field's classes are instantiated correctly first. Also to ensure the fields are subsequently serialised correctly the model dump is configured to use objects that work for json (converting the enums to strings)

fix: resolve pydantic warnings for serialisation

---

scripts/get_concept.py

This was failing for me. Not sure when it started.
```shell
just get-concept Q1363
uv run python scripts/get_concept.py --wikibase-id Q1363
╭──────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ /Users/jesse/src/github.com/climatepolicyradar/knowledge-graph/scripts/get_concept.py:54 in <module>              │
│                                                                                                                   │
│   51                                                                                                              │
│   52                                                                                                              │
│   53 if __name__ == "__main__": …
```

fix: Parse concept as Wikibase ID

---

tests/flows/conftest.py

The tests used in aggregate have had several issues with read timeouts. It turns out that this is due to the way we were cleaning up the bucket, seemingly doing one at a time was resulting in objects not being cleaned up fast enough.
As well as now doing clean up in bulk, this also sets the objects to clear up as teardown of their creation, rather than the bucket itself.

fix: flakey test teardown

---

flows/aggregate.py
flows/index.py
flows/utils.py
tests/flows/conftest.py
tests/flows/test_aggregate.py
tests/flows/test_index.py
tests/flows/test_utils.py

+ Update `collect_unique_file_stems_under_prefix` to be asnyc (utils)
+ Update dependency `collect_stems_by_specs` (aggregate)
+ Update dependency `load_async_json_data_from_s3` (index)
+ Removed references to `mock_bucket` and `mock_s3_client` when not needed - already created by `mock_bucket_inference_results`
+ Refactored `mock_async_bucket` to remove unpacking tuple and added teardown to remove files from s3 
+ Added new fixture `mock_bucket_stem` to simplify test

Update collect_unique_file_stems_under_prefix and dependencies to be async

---

knowledge_graph/wikibase.py
pyproject.toml
uv.lock

Context: Last week, I moved our concept store documentation into wikibase as a series of Help pages, eg [Help:Hierarchy_heuristics](https://climatepolicyradar.wikibase.cloud/wiki/Help:Hierarchy_heuristics)
This PR gives us the ability to:
- search for those pages
- retrieve the content of the pages as markdown
- also search for concepts
These methods alone aren't super interesting... But it's very easy to build an MCP server around a class like this these days, and I think that's where they _could_ start becoming useful 👀
If, at some point in the future, we want to give LLM agents direct access to our concept store data, I reckon they'll benefit _a lot_ from having access to all of the good thinking in eg [our style guide](https://climatepolicyradar.wikibase.cloud/wiki/Help:Style_guide)... …

Search for concepts and help pages through a WikibaseSession

---

flows/inference.py
flows/utils.py
tests/flows/conftest.py
tests/flows/test_boundary.py
tests/flows/test_inference.py
tests/flows/test_utils.py

+ Update Generator import in conftest
+ Remove unused functions in utils
+ Update download_s3_file in inference to be async and update dependencies and tests
+ Update store_labels in inference with tests and create new fixture to teardown bucket
+ Update get_bucket_paginator, list_bucket_file_stems in inference and s3_file_exists in utils (dependency), related bucket fixtures updated to be async, add pyright ignore to resolve before PR review
+ Update boundary tests for s3 to use async 
+ Remove unused fixtures from conftest
+ Refactor teardown by creating a function to remove objects from s3 bucket that is called as part of the teardown of `mock_async_bucket` instead of at the end of each downstream fixture
+ Refactor `get_latest_ingest_documents` to set type on `matching_files` and …

Update flows s3 interactions as async

---

knowledge_graph/identifiers.py

The changes in #677 fail on their own, necessitating an update to the validators on our identifier classes.
In this PR, I've updated the validation methods to use the new pydantic_core structure, and replaced `__get_validators__` with `__get_pydantic_core_schema__`. These changes should enable future development with frameworks which aren't compatible with the older versions of pydantic, without breaking any of our existing code 🤞
More documentation on the pydantic v2 changes here: https://docs.pydantic.dev/latest/internals/architecture/

Use pydantic v2's core schema in identifier classes

---

flows/wikibase_to_s3.py
tests/flows/conftest.py
tests/flows/test_wikibase_to_s3.py

+ Update `wikibase_to_s3` to be async and update the cdn fixture to include a teardown, replicating steps from mock_async_bucket
+ Update `mock_wandb` fixture to also use async s3 client
+ Scripts have been left as synchronous as not much to gains in speed from moving to async
CLOSES PLA-720

Update wikibase_to_s3 and dependencies to be async

---

Dockerfile
deployments.py
flows/config.py
flows/train.py
flows/utils.py
justfile
knowledge_graph/classifier/targets.py
pyproject.toml
scripts/deploy.py
scripts/train.py
uv.lock

This updates the training script to support running training within a prefect flow using coiled. Meaning that Targets can be trained using a gpu. [Prefect run](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/068c9601-95a1-7f85-8000-33a57e18f3ff?entity_id=068c9601-95a1-7f85-8000-33a57e18f3ff&state=cancelled&state=cancelling&state=crashed&state=failed&state=paused&state=pending&state=running&state=scheduled&state=completed&entity=artifacts&entity=flowRuns).
Coiled screenshot showing it ran on a gpu:
Some highlights to draw attention to:
- The image build now is larger — this is unavoidable if we want to run with gpus we need cuda. I would like to try and follow up with some optimisations though... if I can …

feat: enable training with gpus on coiled

---

flows/aggregate.py

Looking at `process_document`, there's no `document_id` any more. There is
`document_stem` though.

fix: Use new arg name for task name

---

flows/classifier_specs/v2/prod.yaml

I've left https://github.com/climatepolicyradar/knowledge-graph/pull/702 in this branch because of the pain from ci for deploying these small changes twice. Also they are related so it makes some sense.
Retraining means we are now including `classifiers_profiles` on Q639, will this be safe to go through with? Or will we need it on all of them classifiers now?

fix: disable Q53, retrain Q639

---

knowledge_graph/span.py
tests/test_span.py

Small fix for `Span.from_xml` (used by LLM classifiers which return `<concept>` tags) for when no concepts are annotated in the text.

Fix Span.from_xml when there are no annotations

---

flows/classifier_specs/spec_interface.py

It's often useful to generate a json version of the specs, I've found myself doing this on occasions when wanting this as a parameter for prefect.
I'm resisting adding this as a script, it just seems like overkill. But the function can be imported in a terminal python session and run when needed and I think thats sufficient for now.

feat: add json conversion function

---

.github/workflows/cd.yml

Currently on merge to main, we deploy sandbox, then we redeploy sandbox before deploying everything else. Deploys can take over 5 minutes each so this is pretty painful. Its still a good check that deploys are valid before trying to deploy to other envs so Im just taking out the last deploy to sandbox

ci: don't redeploy sandbox

---

flows/inference.py

Try to address the `RequestTimeTooSkewed` error [observed in inference runs](https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/068cc263-70f1-7381-8000-b77741cad11b?entity_id=068cc263-70f1-7381-8000-b77741cad11b&state=cancelled&state=cancelling&state=crashed&state=failed&entity=flowRuns&entity=taskRuns&entity=artifacts&log-level=40) by limiting the number of async requests made to 200.
Set semaphore sessions to 200 as [s3 allows 5500 requests per second](https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html) and we are running 1000 docs per batch and around ~20 batches for all documents in the full pipeline.

Add semaphore for run_classifier_inference async task

---

flows/utils.py

`get_logger` returns a standard Python logger[^3].
The intent is to give someone a function that they can call from code running on Prefect via ECS or Prefect via Coiled or literally anywhere.
> Get a prefect logger. These loggers are intended for internal use within the prefect package.[^4]
Prefect's documentation does say this. A _Prefect logger_ is one that is named as `prefect`[^5]. I think we still want this, despite the internal use mention, since in ECS they currently show up as a Prefect logger, so why not have it show up with the same name, even when not in a flow or task run context? **Update:** I don't feel strongly about this at all actually. As long as the fallback is a Python logger, I don't mind which one it is. Maybe we don't actually want it to be a Prefect one, so …

refactor: Add function to get logger with fallback

---

flows/aggregate.py
flows/boundary.py

Seeing these, only in ECS, makes it extremely hard to track down where they came from. I haven't successfully been able to do so.
The print statements are in a Prefect task, that doesn't have `log_prints` set to `True`. That task is being called from a flow that _does_ have that set, but I guess it doesn't carry down to tasks.

fix: Add more debug info

---

flows/inference.py
scripts/train.py
tests/flows/test_inference.py

Adds some initial, extra logging for these errors, for starters it will tell us how skewed the requests are getting.
Also includes a driveby fix for a typo in the train script — ci feels too painful right now to have a whole run just for it.

fix: add logging for `RequestTimeTooSkewed` error

---

.github/workflows/ci.yml

---
Attempts to work towards a reduction in deploy times via a potential quick win by running steps in parallel (flow code storage spike to come after). We could half our deployment times by simply running the deploy flow in parallel rather than in series with the test and linting actions. 
_I don't personally have any worries with running them in parallel - what's the worst case scenario; some code that fails unit tests get's pushed to sandbox?_

Run deploy in parallel with lint and test.

---

.github/workflows/prefect_deploy_labs.yml

This is useful generally and the present motivation is in order to assist: https://github.com/climatepolicyradar/knowledge-graph/pull/777

ci: allow ad hoc branch deployment to labs

---

.github/workflows/prefect_deploy.yml
deployments.py
justfile
pyproject.toml
uv.lock

This uses the same logging approach as in the automation script.
Originally I did this so I could get insight into what was being deployed, as I noticed our deployments are on an old version. I then found a bug in the script, which is now fixed.
I separated deployments and automations so it's easier to separate in CD on GitHub.
**Test**
```
$ AWS_ENV=sandbox uv run python -m deployments
Built knowledge-graph @ file:///Users/jesse/src/github.com/climatepolicyradar/knowledge-graph
Uninstalled 1 package in 3ms
Installed 1 package in 3ms
using version: 0.8.0
15:24:38.654 | INFO    | __main__ - using version: 0.8.0
Successfully created/updated all deployments!
Deployments
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ Name                                 ┃ Status  ┃ Details ┃ …
```

ci: Log version used for Prefect and correctly run deployments
